FROM debian:buster
MAINTAINER Mattias Fliesberg <mattias@fliesberg.email>

WORKDIR /root/opmuse

COPY . /tmp/opmuse

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i "s/buster main/buster main contrib non-free/" /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y curl wget locales apt-transport-https python3 python3-pip python3-pkg-resources \
        gnupg ffmpeg imagemagick rsync git zsh vim procps && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "export LC_ALL=en_US.utf8" >> /root/.bashrc && \
    dpkg-reconfigure locales && \
    echo "mysql-server mysql-server/root_password password" | debconf-set-selections && \
    echo "mysql-server mysql-server/root_password_again password" | debconf-set-selections && \
    apt-get install -y default-mysql-server default-libmysqlclient-dev && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y nodejs && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y yarn && \
    /etc/init.d/mysql start && \
    cd /root && \
    git clone /tmp/opmuse && \
    cd opmuse && \
    cp /tmp/opmuse/.git/config .git/config && \
    rm -rf /tmp/opmuse && \
    pip3 install -r requirements.txt && \
    pip3 install -r mysql-requirements.txt && \
    pip3 install -r dev-requirements.txt && \
    cp config/opmuse.dist.ini config/opmuse.ini && \
    yarn && \
    yarn build:dev && \
    sed -i "s/^\(database\.url\)/#\1/; s/^#\(database\.url = 'mysql\)/\1/" config/opmuse.ini && \
    sed -i "s/^#\(server.socket_host = \).*/\1'0.0.0.0'/" config/opmuse.ini && \
    ./console database create && \
    ./console database fixtures

COPY scripts/docker-dev-start.sh /start.sh

ENTRYPOINT ["/start.sh"]

EXPOSE 8080
