#!/bin/sh

. /etc/dbconfig-common/opmuse.conf

if [ $dbc_dbserver = '' ]; then
    dbc_dbserver='localhost'
fi

dsn="mysql+oursql:\/\/$dbc_dbuser:$dbc_dbpass@$dbc_dbserver\/$dbc_dbname"

sed -i "s/^[ ]*database\.url[^=]*=.*/database.url = '$dsn'/" /etc/opmuse/opmuse.ini

opmuse-console database create
