#!/bin/sh

set -e

. /etc/default/opmuse

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/config.mysql
    dbc_go opmuse $@
fi

db_version 2.0

db_input critical opmuse/library_path || true
db_go

db_input critical opmuse/library_path_perms || true
db_go

db_input critical opmuse/user_name || true
db_input critical opmuse/user_mail || true
db_input critical opmuse/user_pass || true
db_go

db_input high opmuse/socket_host || true
db_input high opmuse/socket_port || true
db_go

db_get opmuse/library_path
library_path=$RET

db_get opmuse/library_path_perms
library_path_perms=$RET

db_get opmuse/socket_host
socket_host=$RET

db_get opmuse/socket_port
socket_port=$RET

if [ ! -d $library_path ]; then
    mkdir -p $library_path
    chown $USER $library_path
fi

if [ "$library_path_perms" = "true" ]; then
    chown -R $USER $library_path
fi

# escape forward slash
library_path=$(echo $library_path | sed 's/[\/&]/\\&/g')

sed -i "s/^[ ]*\(library\.path[^=]*=\).*/\1 '$library_path'/" /etc/opmuse/opmuse.ini
sed -i "s/^[#]*\(server\.socket_host[^=]*=\).*/\1 '$socket_host'/" /etc/opmuse/opmuse.ini
sed -i "s/^[#]*\(server\.socket_port[^=]*=\).*/\1 $socket_port/" /etc/opmuse/opmuse.ini
